### ISSUE TITLE
Use Netcentric/stylelint-config

### ISSUE THREAD

**Issue by quicoto** [Netcentric/fe-build#40]
Should this project include https://github.com/Netcentric/stylelint-config as dependency?

**Comment by petar-prog91** [comment]
Maybe make it configurable (as an option, rather enforcing as default). I would prefer not to couple.

**Comment by raohmaru** [comment]
IMHO, we should not enforce a linter configuration neither add an option. A project can easily create a .stylelintrc file and define there its configurations.

**Comment by quicoto** [comment]
Agreed, closing
