### ISSUE TITLE
Update stylelint: Breaking change, scss not supported ootb

### ISSUE THREAD

**Issue by easingthemes** [Netcentric/fe-build#49]
### Expected Behaviour
no vulnerabilities coming from stylelint v13
check: https://stylelint.io/migration-guide/to-14/
- remove syntax from stylelint config
- add info about breaking change 
- breaking change affect project using this tool (requires additional config/package https://stylelint.io/migration-guide/to-14/), tool itself doesn't need any other changes
### Actual Behaviour
still using v13

**Comment by raohmaru** [comment]
With the current stylelint v13 it is not possible to extend the configuration from @netcentric/stylelint-config, because it uses v14 and new rules introduced at v14 will raise a "Unknown rule" error and stop SASS compiling process, even if `stylelint.failOnError` is `true`.
