### ISSUE TITLE
Use a positive statement

### ISSUE THREAD

**Issue by quicoto** [Netcentric/fe-build#6]
**utils/renderPostcss.js** 

Refactor to use a positive statement instead.

From

```const map = !config.general.isProduction ? { inline: input.map.toString() } : false;```

To:

```const map = config.general.isProduction ? false : { inline: input.map.toString() } ;```

**Comment by Egnus** [comment]
Totally agree with this.
I also would add that, when one of the results of the ternary operator is boolean you can simplify this with only && or || operators. in this case this is clearer and simpler:

```
const map = config.general.isProduction && { inline: input.map.toString() } ;
```
The possible results are `false || { inline: input.map.toString() } ` which is the expected output

**Comment by quicoto** [comment]
For me this ternary version is less readable. I know it works but I have to spend more time reading the line to know what the return is. Don't know I'm wired this way 😁

**Comment by Egnus** [comment]
What do you mean by "ternary is less readable"?
Ternary is `const x = boolean ? caseA : caseB`
But what I did is a conditional assignment `const x = boolean && caseA`

**Comment by Egnus** [comment]
In any case you are right, ternaries are easier to read.
+1 for maintainability.
