### ISSUE TITLE
Update dependencies to avoid vulnerabilities

### ISSUE THREAD

**Issue by amglebihan** [Netcentric/fe-build#60]
### Expected Behaviour
Update the necessary npm packages to avoid having vulnerabilities
Full log listed below

### Actual Behaviour
14 vulnerabilities (4 moderate, 10 high) are found when running npm i

#### Platform and Version
Node v16.4.2 (npm v8.5.0)

#### Logs taken while reproducing problem
# npm audit report

glob-parent  <5.1.2
Severity: high
Regular expression denial of service in glob-parent - https://github.com/advisories/GHSA-ww39-953v-wcq6
fix available via `npm audit fix`
node_modules/watchpack-chokidar2/node_modules/glob-parent
  chokidar  1.0.0-rc1 - 2.1.8
  Depends on vulnerable versions of glob-parent
  node_modules/watchpack-chokidar2/node_modules/chokidar
    watchpack-chokidar2  *
    Depends on vulnerable versions of chokidar
    node_modules/watchpack-chokidar2
      watchpack  1.7.2 - 1.7.5
      Depends on vulnerable versions of watchpack-chokidar2
      node_modules/watchpack
        webpack  4.44.0 - 4.46.0
        Depends on vulnerable versions of watchpack
        node_modules/webpack

node-sass  2.0.0 - 6.0.1
Severity: high
Improper Certificate Validation in node-sass - https://github.com/advisories/GHSA-r8f7-9pfq-mjmv
Depends on vulnerable versions of meow
Depends on vulnerable versions of node-gyp
No fix available
node_modules/node-sass
  @nc/fe-build  *
  Depends on vulnerable versions of node-sass
  node_modules/@nc/fe-build

postcss  <7.0.36
Severity: moderate
Regular Expression Denial of Service in postcss - https://github.com/advisories/GHSA-566m-qj78-rww5
fix available via `npm audit fix`
node_modules/@nc/fe-build/node_modules/stylelint-no-unsupported-browser-features/node_modules/postcss
  stylelint-no-unsupported-browser-features  <=3.0.0
  Depends on vulnerable versions of postcss
  node_modules/@nc/fe-build/node_modules/stylelint-no-unsupported-browser-features
    @nc/stylelint-config  2.0.0
    Depends on vulnerable versions of stylelint-no-unsupported-browser-features
    node_modules/@nc/fe-build/node_modules/@nc/stylelint-config

tar  <=4.4.17
Severity: high
Arbitrary File Creation/Overwrite via insufficient symlink protection due to directory cache poisoning using symbolic links - https://github.com/advisories/GHSA-qq89-hq3f-393p
Arbitrary File Creation/Overwrite via insufficient symlink protection due to directory cache poisoning using symbolic links - https://github.com/advisories/GHSA-9r2w-394v-53qc
Arbitrary File Creation/Overwrite due to insufficient absolute path sanitization - https://github.com/advisories/GHSA-3jfq-g458-7qm9
Arbitrary File Creation/Overwrite via insufficient symlink protection due to directory cache poisoning - https://github.com/advisories/GHSA-r628-mhmh-qjhw
No fix available
node_modules/tar
  node-gyp  <=3.8.0
  Depends on vulnerable versions of tar
  node_modules/node-gyp
    node-sass  2.0.0 - 6.0.1
    Depends on vulnerable versions of meow
    Depends on vulnerable versions of node-gyp
    node_modules/node-sass
      @nc/fe-build  *
      Depends on vulnerable versions of node-sass
      node_modules/@nc/fe-build

trim-newlines  <3.0.1
Severity: high
Regular Expression Denial of Service in trim-newlines - https://github.com/advisories/GHSA-7p7h-4mm5-852v
No fix available
node_modules/node-sass/node_modules/trim-newlines
  meow  3.4.0 - 5.0.0
  Depends on vulnerable versions of trim-newlines
  node_modules/node-sass/node_modules/meow
    node-sass  2.0.0 - 6.0.1
    Depends on vulnerable versions of meow
    Depends on vulnerable versions of node-gyp
    node_modules/node-sass
      @nc/fe-build  *
      Depends on vulnerable versions of node-sass
      node_modules/@nc/fe-build

**Comment by easingthemes** [comment]
Can't be done standalone, it all depends on Webpack upgrade https://github.com/Netcentric/fe-build/issues/31.
