### ISSUE TITLE
How to use with React

### ISSUE THREAD

**Issue by quicoto** [Netcentric/fe-build#71]
Would be nice to document the minimal config changes needed to make this work with React or another framework

**Comment by easingthemes** [comment]
React example:
1. disable clientlibs if it's non AEM application `defaultTasks: ["styles", "webpack"],`
2. Install `@babel/preset-react`
3. Add `@babel/preset-react` to babel config:

```module.exports = {
  general: {
    defaultTasks: ["styles", "webpack"],
  },
  babel: {
    use: {
      options: {
        presets: [
          "@babel/preset-env",
          "@babel/preset-react"
        ]
      }
    }
  },
```

This config was test on existing PROD React SPA.

**Comment by quicoto** [comment]
Thank you, closing issue
