### ISSUE TITLE
Support for sass alias needed

### ISSUE THREAD

**Issue by rogercornet** [Netcentric/fe-build#96]
### Expected Behaviour
Imports like
```scss
import '@common/common';
``` 
should be supported and configurable in `.febuild`.

### Actual Behaviour
An error on the build is thrown if an import like the one below is found:
```scss
import '@common/common';
``` 

#### Platform and Version
version 3.0.2

**Comment by easingthemes** [comment]
What is sass alias?
Do you mean a plugin: https://www.npmjs.com/package/sass-alias?

We currently support sass include paths, you can use short path in import, relative to defined include paths.

```
import 'common';
```

configuring `.febuild`:
```
  sass: {
      includePaths: [
        '/path/to/any/dir/'
      ]
  },
```
